USE vnla
GO

INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'CHITHI', N'Chỉ thị')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'CONGVAN', N'Công văn')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'CONGUOC', N'Công ước')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'HIENCHUONG', N'Hiến chương')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'HIENPHAP', N'Hiến pháp')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'HIEPDINH', N'Hiệp định')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'HIEPUOC', N'Hiệp ước')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'HUONGDAN', N'Hướng dẫn')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'LUAT', N'Luật')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'NGHIQUYET', N'Nghị quyết')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'NGHIDINH', N'Nghị định')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'NGHIDINHTHU', N'Nghị định thư')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'PHAPLENH', N'Pháp lệnh')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'QUYCHE', N'Quy chế')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'QUYDINH', N'Quy định')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'QUYETDINH', N'Quyết định')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'SACLUAT', N'Sắc luật')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'SACLENH', N'Sắc lệnh')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'THOATHUAN', N'Thỏa thuận')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'THONGBAO', N'Thông báo')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'THONGTRI', N'Thông tri')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'THONGTU', N'Thông tư')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'THONGTUBIENTICH', N'Thông tư biên tịch')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'TUYENBOCHUNG', N'Tuyên bố chung')
INSERT INTO tblDanhmucvanban(PK_sDanhmucvanbanID, sTendanhmuc)
VALUES(N'DIEULE', N'Điều lệ')


----Co Quan
INSERT INTO tblCoquan(PK_sCoquanID, sTencoquan)
VALUES(N'QH', N'Quốc Hội')
INSERT INTO tblCoquan(PK_sCoquanID, sTencoquan)
VALUES(N'TTCP', N'Thủ tướng chính phủ')
INSERT INTO tblCoquan(PK_sCoquanID, sTencoquan)
VALUES(N'CTN', N'Chủ tịch nước')